# Burlap Sack
modLoader="javafml"
loaderVersion="[37,)"
license="Apache-2.0 License"
issueTrackerURL="https://github.com/yorkeJohn/Burlap-Sack/issues"
[[mods]]
  modId="burlapsack"
  version="1.17.1-1.0"
  displayName="Burlap Sack"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/burlap-sack"
  logoFile="burlap_sack_logo.png"
  authors="tadashi_3"
  description='''Adds a simple way to transport animals and villagers using a burlap sack.'''
[[dependencies.burlapsack]]
  modId="forge"
  mandatory=true
  versionRange="[37,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.burlapsack]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.17.1,)"
  ordering="NONE"
  side="BOTH"
